export const shop = {
  lastItem: { itemId: "beard2_brown", cost: 20 },
  freeItem: { itemId: "goggles_pink", cost: 0 },
  nextItem: { itemId: "scout_uniform", cost: 0 },
  collection: [
    { itemId: "santa_hat", cost: 100 },
  ],
};

export const codes = {
  rocketsnail: ["viking", "rocket_red"],
  andybulletin: "propeller",
  cute: "toque_pink",
  oommgames: "space_red",
  boxcritters3d: ["3d_white", "3d_black"],
  goodnight: "sleeping",
  madeincanada: "toque_white",
  thekeeper: "party_green",
  bunnyhug: "hoodie_blue",
  greenplumber: "ballcap_green",
  duckhunter: "float_pink",
  piratepack: "pirate_patch",
  pickle: "pickle",
  oscarproductions: "guitar_blue",
  livestream: "headphones_black",
  creative: "headphones_black",
  fun: "propeller_pink",
  marco: "keytar_red",
  snowball: "hoodie_white",
  critbits: "ballcap_pink",
  esporte: "kit_yellow",
  squeeze: "hoodie_orange",
  imagination: "box_brown",
  sparkle: "propeller_silver",
  adventure: "snorkel_blue",
  tamago: "sun_square",
  redcross: "australian_hat",
  discordcritterspt: "headphones_green",
  scarletraven: "wings_black",
  boxcritterswiki: "paperhat_colour",
  wikicritters: "brain_green",
  boxcrittersguild: "cardboard_sword_silver",
  staysafe: "doctor_mask_blue",
  glitter: "pirate_capt_pink",
};

export const throwback = [
  "goggles_black",
  "pot",
  "sombrero_yellow",
  "cone",
  "toque_purple",
  "sun_orange",
  "pirate_capt_black",
  "lifejacket_red",
  "ballcap_black",
  "super_cape_red",
  "tshirt_white",
  "lei_red",
  "ballcap_blue",
  "viking_blue",
  "overalls_orange",
  "bunny_blue",
  "messenger_brown",
  "plaid_black",
  "tinfoil_hat",
  "monk",
  "pirate_hat_black",
  "hawaii_orange",
  "space_black",
  "traffic_cone",
  "grass_yellow",
  "ushanka",
  "bandana_purple",
  "ski_suit_blue",
  "hotdog",
  "space_blue",
  "sweater_orange",
  "tactical_headset",
  "ballcap_yellow",
  "ringmaster_suit_red",
  "flight_helmet_red",
  "rainhat_yellow",
  "raincoat_yellow",
  "ballcap_red",
  "ballerina_pink",
  "hawaii_blue",
  "stripe_red_white",
  "grass_green",
  "plaid_blue",
  "toque_orange",
  "school_pack_orange",
  "pirate_crew_blue",
  "ringmaster_hat_black",
  "super_mask_black",
  "pirate_hat_pink",
  "rainhat_red",
  "tophat_black",
  "scarf_red",
  "skeleton_body",
  "dracula_cloak",
  "pumpkin",
  "hotdog",
  "beard3_black",
  "scarf_purple",
  "puffy_red",
  "blockhead",
  "hoodie_purple",
  "winter_dress_red",
  "bulb_blue",
  "tacky_red",
  "pirate_bandana_red",
];

export const eventCodes = {
  christmas2019: {
    jinglebells: "elf_hat_green",
    winter: "winter_dress",
    joy: "bulb_yellow",
    rudolph: "reindeer_head",
    elf: "elf_suit_green",
    cheer: "bulb_green",
    glow: "bulb_red",
    rednose: "reindeer_body",
    blizzard: "wizard_blizzard",
    family: "ornament_red",
    shine: "angel_halo",
    peace: "angel_wings",
    jolly: "santa_beard",
    merry: "santa_hat",
    christmas: "santa_suit",
    boxingday: "onsie_plaid_red",
    warm: "sleeping_red",
    tacky: "tacky_green",
    snow: "goggles_white",
    beautiful: "winter_dress_red",
    newyear: "tuxedo_black",
    "2020": "tophat_black",
  },
};
